// Copyright (c) 2023 Philippe Matray. All rights reserved.
// This file is part of TaLibStandard.
// TaLibStandard is licensed under the GNU General Public License v3.0.
// See the LICENSE file in the project root for the full license text.
// For more information, visit https://github.com/phmatray/TaLibStandard.

using TechnicalAnalysis.Samples.RealTime.Contracts;

namespace TechnicalAnalysis.Samples.RealTime.Diagnostics;

/// <summary>
/// Every log message the sample emits, declared once and generated by the logging source generator.
/// </summary>
/// <remarks>
/// Source generated logging keeps message templates in one place, allocates nothing when a level is
/// disabled, and skips the boxing that the <c>LogInformation(string, params object?[])</c> overloads do on
/// every call. On a per-bar path that matters; in a sample it also documents exactly what the server says
/// about itself.
/// </remarks>
internal static partial class SampleLog
{
    [LoggerMessage(
        EventId = 1000,
        Level = LogLevel.Information,
        Message = "Synthetic feed starting for {SymbolCount} symbol(s) at one tick every {IntervalMilliseconds} ms.")]
    public static partial void FeedStarting(ILogger logger, int symbolCount, double intervalMilliseconds);

    [LoggerMessage(EventId = 1001, Level = LogLevel.Information, Message = "Synthetic feed stopped after {TickCount} tick(s).")]
    public static partial void FeedStopped(ILogger logger, long tickCount);

    [LoggerMessage(
        EventId = 1100,
        Level = LogLevel.Information,
        Message = "Indicator pipeline running: {BarSeconds}s bars, {WindowSize}-bar window, "
            + "{BarsRequired} bars until every indicator is warm.")]
    public static partial void PipelineStarted(ILogger logger, int barSeconds, int windowSize, int barsRequired);

    [LoggerMessage(EventId = 1101, Level = LogLevel.Information, Message = "Indicator pipeline stopped after {BarCount} bar(s).")]
    public static partial void PipelineStopped(ILogger logger, long barCount);

    [LoggerMessage(
        EventId = 1102,
        Level = LogLevel.Debug,
        Message = "{Symbol} bar {Sequence} closed at {Close} ({BarsInWindow}/{BarsRequired} bars, signal {Signal}).")]
    public static partial void BarClosed(
        ILogger logger,
        string symbol,
        long sequence,
        decimal close,
        int barsInWindow,
        int barsRequired,
        Signal signal);

    [LoggerMessage(
        EventId = 1103,
        Level = LogLevel.Warning,
        Message = "SignalR group push for {Symbol} bar {Sequence} exceeded {TimeoutMilliseconds} ms and was dropped; "
            + "a subscriber has stopped reading.")]
    public static partial void PushTimedOut(ILogger logger, string symbol, long sequence, double timeoutMilliseconds);

    [LoggerMessage(EventId = 1200, Level = LogLevel.Information, Message = "WebSocket client subscribed to {Symbol}.")]
    public static partial void WebSocketSubscribed(ILogger logger, string symbol);

    [LoggerMessage(EventId = 1201, Level = LogLevel.Information, Message = "WebSocket client for {Symbol} dropped: {Reason}.")]
    public static partial void WebSocketDropped(ILogger logger, string symbol, string reason);

    [LoggerMessage(EventId = 1202, Level = LogLevel.Information, Message = "WebSocket client for {Symbol} disconnected.")]
    public static partial void WebSocketDisconnected(ILogger logger, string symbol);
}
