// Copyright (c) 2023 Philippe Matray. All rights reserved.
// This file is part of TaLibStandard.
// TaLibStandard is licensed under the GNU General Public License v3.0.
// See the LICENSE file in the project root for the full license text.
// For more information, visit https://github.com/phmatray/TaLibStandard.

namespace TechnicalAnalysis.Samples.RealTime.Contracts;

/// <summary>
/// The envelope every frame on the raw <c>/ws/indicators</c> socket uses.
/// </summary>
/// <remarks>
/// SignalR gives clients a method name for free; a raw socket does not, so the sample carries a
/// discriminator instead. Exactly one payload property is populated for a given <paramref name="Type"/>.
/// </remarks>
/// <param name="Type">The frame kind: <c>session</c>, <c>snapshot</c> or <c>error</c>.</param>
/// <param name="Session">Populated for <c>session</c> frames, sent once right after the upgrade.</param>
/// <param name="Snapshot">Populated for <c>snapshot</c> frames, one per closed bar.</param>
/// <param name="Error">Populated for <c>error</c> frames, describing why the socket is about to close.</param>
public sealed record StreamMessage(
    string Type,
    SessionInfo? Session = null,
    IndicatorSnapshot? Snapshot = null,
    string? Error = null)
{
    /// <summary>The <see cref="Type"/> value of the opening handshake frame.</summary>
    public const string SessionType = "session";

    /// <summary>The <see cref="Type"/> value of a per-bar indicator frame.</summary>
    public const string SnapshotType = "snapshot";

    /// <summary>The <see cref="Type"/> value of a terminal error frame.</summary>
    public const string ErrorType = "error";

    /// <summary>Creates the opening handshake frame.</summary>
    /// <param name="session">The session description to send.</param>
    /// <returns>A <c>session</c> frame.</returns>
    public static StreamMessage ForSession(SessionInfo session) => new(SessionType, Session: session);

    /// <summary>Creates a per-bar indicator frame.</summary>
    /// <param name="snapshot">The snapshot to send.</param>
    /// <returns>A <c>snapshot</c> frame.</returns>
    public static StreamMessage ForSnapshot(IndicatorSnapshot snapshot) => new(SnapshotType, Snapshot: snapshot);

    /// <summary>Creates a terminal error frame.</summary>
    /// <param name="error">A human readable reason.</param>
    /// <returns>An <c>error</c> frame.</returns>
    public static StreamMessage ForError(string error) => new(ErrorType, Error: error);
}

/// <summary>
/// What the server tells a freshly connected socket about itself, so the page can label its axes and
/// legends from configuration instead of hard-coding periods.
/// </summary>
/// <param name="Symbol">The symbol this socket is subscribed to.</param>
/// <param name="Symbols">Every symbol the server publishes.</param>
/// <param name="BarSeconds">The bar period, in seconds.</param>
/// <param name="TickIntervalMilliseconds">The interval between synthetic ticks, in milliseconds.</param>
/// <param name="WindowSize">The number of bars the rolling indicator window keeps.</param>
/// <param name="Periods">The configured indicator periods.</param>
public sealed record SessionInfo(
    string Symbol,
    IReadOnlyList<string> Symbols,
    int BarSeconds,
    int TickIntervalMilliseconds,
    int WindowSize,
    IndicatorPeriods Periods);

/// <summary>
/// The indicator periods in force on the server.
/// </summary>
/// <param name="SmaFast">Fast simple moving average period.</param>
/// <param name="SmaSlow">Slow simple moving average period.</param>
/// <param name="Ema">Exponential moving average period.</param>
/// <param name="Rsi">Relative strength index period.</param>
/// <param name="MacdFast">MACD fast period.</param>
/// <param name="MacdSlow">MACD slow period.</param>
/// <param name="MacdSignal">MACD signal period.</param>
/// <param name="Bollinger">Bollinger band period.</param>
/// <param name="BollingerDeviations">Bollinger band standard deviation multiplier.</param>
/// <param name="Atr">Average true range period.</param>
public sealed record IndicatorPeriods(
    int SmaFast,
    int SmaSlow,
    int Ema,
    int Rsi,
    int MacdFast,
    int MacdSlow,
    int MacdSignal,
    int Bollinger,
    double BollingerDeviations,
    int Atr);

/// <summary>
/// The payload of <c>GET /health</c>.
/// </summary>
/// <param name="Status">Always <c>healthy</c> once the host is serving.</param>
/// <param name="ServerTimeUtc">The server clock, so a client can spot a badly skewed machine.</param>
/// <param name="UptimeSeconds">Seconds since the process started serving.</param>
/// <param name="Symbols">Every symbol the server publishes.</param>
/// <param name="TicksPublished">Ticks generated by the synthetic feed since start.</param>
/// <param name="BarsClosed">Bars closed by the aggregators since start.</param>
/// <param name="TickSubscribers">Live tick subscribers, which should equal the number of running pipelines.</param>
/// <param name="SnapshotSubscribers">
/// Live snapshot <em>channel</em> subscribers across all symbols: raw WebSocket clients and hub streaming
/// callers. It does not cover the SignalR push transport, whose subscribers hold a group membership rather
/// than a channel — see <paramref name="GroupSubscribers"/>.
/// </param>
/// <param name="GroupSubscribers">
/// Live SignalR push subscriptions across all symbols, one per connection per subscribed symbol.
/// </param>
/// <param name="PushesDropped">
/// Bars the SignalR push transport discarded because a group did not accept them in time. Non-zero means a
/// subscriber stopped reading; the other transports are unaffected.
/// </param>
public sealed record HealthResponse(
    string Status,
    DateTimeOffset ServerTimeUtc,
    double UptimeSeconds,
    IReadOnlyList<string> Symbols,
    long TicksPublished,
    long BarsClosed,
    int TickSubscribers,
    int SnapshotSubscribers,
    int GroupSubscribers,
    long PushesDropped);
